services:
  db:
    container_name: db_mysql
    image: mysql:9.1.0
    volumes:
      - ./vol:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: always
  
  phpMyAdmin:
    depends_on:
      - db
    container_name: dbAdmin
    image: phpmyadmin:5.2.0-apache
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
     
volumes:
  event-vol:
    external: false